; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN: llc < %s -mtriple=riscv32 -mcpu=zcb --target-abi ilp32f 2>&1 \
; RUN:     | FileCheck %s -check-prefix=RV32
; RUN: llc < %s -mtriple=riscv32 -mattr=+f -mattr=+zcb -mattr=+v --target-abi ilp32f 2>&1 \
; RUN:     | FileCheck %s -check-prefix=RV32

declare void @llvm.riscv.veadd.mm(half* %d, half* %s1, half* %s2)

define void @foo0(half* %a, half* %b, half* %c) {
; RV32-LABEL: foo0:
; RV32:       # %bb.0:
; RV32-NEXT:    veadd.mm (a0), (a1), (a2)
; RV32-NEXT:    ret
  tail call void @llvm.riscv.veadd.mm(half* %a, half* %b, half* %c)

  ret void
}
